#!/bin/bash

alias nano="nano -c"
alias grepsrc="grep --color=auto -rIHn --include=\*.{h,cpp,cs,bindings,pl,pm,c}  --exclude-dir={.hg,.git}"
alias neo="cmatrix"
alias debug="gdb -ex=r --args"
alias ll="ls -al --color=auto -h"
alias xclip="xclip -selection c"
alias du='du -hs'
alias df='df -h'
alias rless="less -R"

unalias l
function l() {
    if [ "$1" = "" ]; then
        ls -alh
    else if [ -f $1 ]; then
        more $1
    else if [ -e $1 ]; then
        ls -alh $1
    else
        echo "Don't know what '$1' is." >&2
    fi; fi; fi
}


