#!/bin/bash
origin="$1"
branch="$2"
if [ -z "$origin" ] || [ -z "$branch" ]; then
    echo "Usage: $0 <origin> <branch>" >&2
    exit 1
fi

files=$(git status -s)
if [ -n "$files" ]; then
    echo "Here's the status of your working tree:"
    git status | head -n 15
    echo "Press any key to erase and checkout $origin/$branch..."
    read -n 1
fi

set -e
echo "Fetching..."
git fetch "$origin" "$branch"
echo "Checkout..."
git checkout "$branch"
echo "Resetting..."
git reset --hard "$origin/$branch"
echo "Updating submodules..."
git submodule update --init --recursive
echo "New status:"
git status

